import { Extension, textInputRule } from "@tiptap/core";

const Glyphs = Extension.create({
  name: "Glyphs",

  addInputRules() {
    return [
      textInputRule({ find: /-- $/, replace: "— " }),
      textInputRule({ find: /\.{3}$/, replace: "…" }),
      textInputRule({ find: /←-$/, replace: "⟵" }),
      textInputRule({ find: /<-$/, replace: "←" }),
      textInputRule({ find: /-->$/, replace: "⟶" }),
      textInputRule({ find: /->$/, replace: "→" }),
      textInputRule({ find: /⟵>$/, replace: "⟷" }),
      textInputRule({ find: /←>$/, replace: "🡘" }),
      textInputRule({ find: /⇐=$/, replace: "⟸" }),
      textInputRule({ find: /<=$/, replace: "⇐" }),
      textInputRule({ find: /==>$/, replace: "⟹" }),
      textInputRule({ find: /=>$/, replace: "⇒" }),
      textInputRule({ find: /⇐>$/, replace: "⇔" }),
      textInputRule({ find: /⟸>$/, replace: "⟺" }),
      textInputRule({ find: /\(c\)$/, replace: "©" }),
      textInputRule({ find: /\(tm\)$/, replace: "™" }),
      textInputRule({ find: /\(r\)$/, replace: "®" }),
      textInputRule({ find: /1\/2 $/, replace: "½ " }),
      textInputRule({ find: /\+\/- $/, replace: "± " }),
      textInputRule({ find: /!= $/, replace: "≠ " }),
      textInputRule({ find: /<< $/, replace: "« " }),
      textInputRule({ find: />> $/, replace: "» " }),
      textInputRule({ find: /\^2 $/, replace: "² " }),
      textInputRule({ find: /\^3 $/, replace: "³ " }),
      textInputRule({ find: /1\/4 $/, replace: "¼ " }),
      textInputRule({ find: /3\/4 $/, replace: "¾ " }),

      /**
       * Smileys
       */
      textInputRule({ find: /-___- $/, replace: "😑 " }),
      textInputRule({ find: /:'-\) $/, replace: "😂 " }),
      textInputRule({ find: /':-\) $/, replace: "😅 " }),
      textInputRule({ find: /':-D $/, replace: "😅 " }),
      textInputRule({ find: />:-\) $/, replace: "😆 " }),
      textInputRule({ find: /-__- $/, replace: "😑 " }),
      textInputRule({ find: /':-\( $/, replace: "😓 " }),
      textInputRule({ find: /:'-\( $/, replace: "😢 " }),
      textInputRule({ find: />:-\( $/, replace: "😠 " }),
      textInputRule({ find: /O:-\) $/, replace: "😇 " }),
      textInputRule({ find: /0:-3 $/, replace: "😇 " }),
      textInputRule({ find: /0:-\) $/, replace: "😇 " }),
      textInputRule({ find: /0;\^\) $/, replace: "😇 " }),
      textInputRule({ find: /O;-\) $/, replace: "😇 " }),
      textInputRule({ find: /0;-\) $/, replace: "😇 " }),
      textInputRule({ find: /O:-3 $/, replace: "😇 " }),
      textInputRule({ find: /:'\) $/, replace: "😂 " }),
      textInputRule({ find: /:-D $/, replace: "😃 " }),
      textInputRule({ find: /':\) $/, replace: "😅 " }),
      textInputRule({ find: /'=\) $/, replace: "😅 " }),
      textInputRule({ find: /':D $/, replace: "😅 " }),
      textInputRule({ find: /'=D $/, replace: "😅 " }),
      textInputRule({ find: />:\) $/, replace: "😆 " }),
      textInputRule({ find: />;\) $/, replace: "😆 " }),
      textInputRule({ find: />=\) $/, replace: "😆 " }),
      textInputRule({ find: /;-\) $/, replace: "😉 " }),
      textInputRule({ find: /\*-\) $/, replace: "😉 " }),
      textInputRule({ find: /;-\] $/, replace: "😉 " }),
      textInputRule({ find: /;\^\) $/, replace: "😉 " }),
      textInputRule({ find: /B-\) $/, replace: "😎 " }),
      textInputRule({ find: /8-\) $/, replace: "😎 " }),
      textInputRule({ find: /B-D $/, replace: "😎 " }),
      textInputRule({ find: /8-D $/, replace: "😎 " }),
      textInputRule({ find: /:-\* $/, replace: "😘 " }),
      textInputRule({ find: /:\^\* $/, replace: "😘 " }),
      textInputRule({ find: /:-\) $/, replace: "🙂 " }),
      textInputRule({ find: /-_- $/, replace: "😑 " }),
      textInputRule({ find: /:-X $/, replace: "😶 " }),
      textInputRule({ find: /:-# $/, replace: "😶 " }),
      textInputRule({ find: /:-x $/, replace: "😶 " }),
      textInputRule({ find: />.< $/, replace: "😣 " }),
      textInputRule({ find: /:-O $/, replace: "😮 " }),
      textInputRule({ find: /:-o $/, replace: "😮 " }),
      textInputRule({ find: /O_O $/, replace: "😮 " }),
      textInputRule({ find: />:O $/, replace: "😮 " }),
      textInputRule({ find: /:-P $/, replace: "😛 " }),
      textInputRule({ find: /:-p $/, replace: "😛 " }),
      textInputRule({ find: /:-Þ $/, replace: "😛 " }),
      textInputRule({ find: /:-þ $/, replace: "😛 " }),
      textInputRule({ find: /:-b $/, replace: "😛 " }),
      textInputRule({ find: />:P $/, replace: "😜 " }),
      textInputRule({ find: /X-P $/, replace: "😜 " }),
      textInputRule({ find: /x-p $/, replace: "😜 " }),
      textInputRule({ find: /':\( $/, replace: "😓 " }),
      textInputRule({ find: /'=\( $/, replace: "😓 " }),
      textInputRule({ find: />:\\ $/, replace: "😕 " }),
      textInputRule({ find: />:\/ $/, replace: "😕 " }),
      textInputRule({ find: /:-\/ $/, replace: "😕 " }),
      textInputRule({ find: /:-. $/, replace: "😕 " }),
      textInputRule({ find: />:\[ $/, replace: "😞 " }),
      textInputRule({ find: /:-\( $/, replace: "😞 " }),
      textInputRule({ find: /:-\[ $/, replace: "😞 " }),
      textInputRule({ find: /:'\( $/, replace: "😢 " }),
      textInputRule({ find: /;-\( $/, replace: "😢 " }),
      textInputRule({ find: /#-\) $/, replace: "😵 " }),
      textInputRule({ find: /%-\) $/, replace: "😵 " }),
      textInputRule({ find: /X-\) $/, replace: "😵 " }),
      textInputRule({ find: />:\( $/, replace: "😠 " }),
      textInputRule({ find: /0:3 $/, replace: "😇 " }),
      textInputRule({ find: /0:\) $/, replace: "😇 " }),
      textInputRule({ find: /O:\) $/, replace: "😇 " }),
      textInputRule({ find: /O=\) $/, replace: "😇 " }),
      textInputRule({ find: /O:3 $/, replace: "😇 " }),
      textInputRule({ find: /<\/3 $/, replace: "💔 " }),
      textInputRule({ find: /:D $/, replace: "😃 " }),
      textInputRule({ find: /=D $/, replace: "😃 " }),
      textInputRule({ find: /;\) $/, replace: "😉 " }),
      textInputRule({ find: /\*\) $/, replace: "😉 " }),
      textInputRule({ find: /;\] $/, replace: "😉 " }),
      textInputRule({ find: /;D $/, replace: "😉 " }),
      textInputRule({ find: /B\) $/, replace: "😎 " }),
      textInputRule({ find: /8\) $/, replace: "😎 " }),
      textInputRule({ find: /:\* $/, replace: "😘 " }),
      textInputRule({ find: /=\* $/, replace: "😘 " }),
      textInputRule({ find: /:\) $/, replace: "🙂 " }),
      textInputRule({ find: /=\] $/, replace: "🙂 " }),
      textInputRule({ find: /=\) $/, replace: "🙂 " }),
      textInputRule({ find: /:\] $/, replace: "🙂 " }),
      textInputRule({ find: /:X $/, replace: "😶 " }),
      textInputRule({ find: /:# $/, replace: "😶 " }),
      textInputRule({ find: /=X $/, replace: "😶 " }),
      textInputRule({ find: /=x $/, replace: "😶 " }),
      textInputRule({ find: /:x $/, replace: "😶 " }),
      textInputRule({ find: /=# $/, replace: "😶 " }),
      textInputRule({ find: /:O $/, replace: "😮 " }),
      textInputRule({ find: /:o $/, replace: "😮 " }),
      textInputRule({ find: /:P $/, replace: "😛 " }),
      textInputRule({ find: /=P $/, replace: "😛 " }),
      textInputRule({ find: /:p $/, replace: "😛  " }),
      textInputRule({ find: /=p $/, replace: "😛 " }),
      textInputRule({ find: /:Þ $/, replace: "😛 " }),
      textInputRule({ find: /:þ $/, replace: "😛 " }),
      textInputRule({ find: /:b $/, replace: "😛 " }),
      textInputRule({ find: /d: $/, replace: "😛 " }),
      textInputRule({ find: /:\/ $/, replace: "😕 " }),
      textInputRule({ find: /:\\ $/, replace: "😕 " }),
      textInputRule({ find: /=\/ $/, replace: "😕 " }),
      textInputRule({ find: /=\\ $/, replace: "😕 " }),
      textInputRule({ find: /:L $/, replace: "😕 " }),
      textInputRule({ find: /=L $/, replace: "😕 " }),
      textInputRule({ find: /:\( $/, replace: "😞 " }),
      textInputRule({ find: /:\[ $/, replace: "😞 " }),
      textInputRule({ find: /=\( $/, replace: "😞 " }),
      textInputRule({ find: /;\( $/, replace: "😢 " }),
      textInputRule({ find: /D: $/, replace: "😨 " }),
      textInputRule({ find: /:\$ $/, replace: "😳 " }),
      textInputRule({ find: /=\$ $/, replace: "😳 " }),
      textInputRule({ find: /#\) $/, replace: "😵 " }),
      textInputRule({ find: /%\) $/, replace: "😵 " }),
      textInputRule({ find: /X\) $/, replace: "😵 " }),
      textInputRule({ find: /:@ $/, replace: "😠 " }),
      textInputRule({ find: /<3 $/, replace: "❤️ " }),

      // Emoji Shortcodes
      textInputRule({ find: /:heart:$/, replace: "❤️ " }),
      textInputRule({ find: /:heart_hands:$/, replace: "🫶 " }),
      textInputRule({ find: /:sparkles:$/, replace: "✨ " }),
      textInputRule({ find: /:party:$/, replace: "🎉 " }),
      textInputRule({ find: /:fire:$/, replace: "🔥 " }),
      textInputRule({ find: /:100:$/, replace: "💯 " }),
      textInputRule({ find: /:poop:$/, replace: "💩 " }),
      textInputRule({ find: /:eyes:$/, replace: "👀 " }),
      textInputRule({ find: /:ghost:$/, replace: "👻 " }),
      textInputRule({ find: /:graduation_cap:$/, replace: "🎓 " }),
      textInputRule({ find: /:thumbsup:$/, replace: "👍 " }),
      textInputRule({ find: /:thumbsdown:$/, replace: "👎 " }),
      textInputRule({ find: /:rocket:$/, replace: "🚀 " }),
      textInputRule({ find: /:salute:$/, replace: "👋 " }),
      textInputRule({ find: /:grinning_face:$/, replace: "😀 " }),
      textInputRule({ find: /:sweat_smile:$/, replace: "😅 " }),
      textInputRule({ find: /:droplet:$/, replace: "💧 " }),
      textInputRule({ find: /:starstruck:$/, replace: "🤩 " }),
      textInputRule({ find: /:sob:$/, replace: "😭 " }),
      textInputRule({ find: /:skull:$/, replace: "💀 " }),
      textInputRule({ find: /:smile:$/, replace: "😄 " }),
      textInputRule({ find: /:rofl:$/, replace: "🤣 " }),
      textInputRule({ find: /:wink:$/, replace: "😉 " }),
      textInputRule({ find: /:candle:$/, replace: "🕯️ " }),
      textInputRule({ find: /:diya_lamp:$/, replace: "🪔 " }),
      textInputRule({ find: /:rainbow:$/, replace: "🌈 " }),
      textInputRule({ find: /:om:$/, replace: "🕉️ " }),
      textInputRule({ find: /:bulb:$/, replace: "💡 " }),
      textInputRule({ find: /:dizzy:$/, replace: "💫 " }),
      textInputRule({ find: /:bomb:$/, replace: "💣 " }),
      textInputRule({ find: /:firecracker:$/, replace: "🧨 " }),
      textInputRule({ find: /:fireworks:$/, replace: "🎆 " }),
      textInputRule({ find: /:alien:$/, replace: "👽 " }),
      textInputRule({ find: /:robot:$/, replace: "🤖 " }),
      textInputRule({ find: /:crystal_ball:$/, replace: "🔮 " }),
      textInputRule({ find: /:chocolate_bar:$/, replace: "🍫 " }),
      textInputRule({ find: /:unicorn:$/, replace: "🦄 " }),
      textInputRule({ find: /:clown_face:$/, replace: "🤡 " }),
    ];
  },
});

export default Glyphs;
